In [117]:
import pandas as pd

## Cargar datos

In [118]:
personal = pd.read_csv("https://raw.githubusercontent.com/anaepm/rep/refs/heads/main/nobel_personal.csv")
personal

,Laureate_Id,Firstname,Lastname,Gender,Birth_Date,Birth_Country,Birth_City,Birth_Country_Code,Death_Date,Death_Country,Death_City,Death_Country_Code,Organization_Name,Organization_City,Organization_Country
0,1,Wilhelm Conrad,Röntgen,male,1845-03-27,Prussia (now Germany),Lennep (now Remscheid),DE,10/02/1923,Germany,Munich,DE,Munich University,Munich,Germany
1,293,Emil,von Behring,male,1854-03-15,Prussia (now Poland),Hansdorf (now Lawice),PL,31/03/1917,Germany,Marburg,DE,Marburg University,Marburg,Germany
2,462,Henry,Dunant,male,1828-05-08,Switzerland,Geneva,CH,30/10/1910,Switzerland,Heiden,CH,NaN,NaN,NaN
3,463,Frédéric,Passy,male,1822-05-20,France,Paris,FR,12/06/1912,France,Paris,FR,NaN,NaN,NaN
4,569,Sully,Prudhomme,male,1839-03-16,France,Paris,FR,07/09/1907,France,Châtenay,FR,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,1011,Svante,Pääbo,male,20/04/1955,Sweden,Stockholm,SE,0000-00-00,NaN,NaN,NaN,Max Planck Institute for Evolutionary Anthropo...,Leipzig,Germany
985,743,Barry,Sharpless,male,28/04/1941,USA,Philadelphia PA,US,0000-00-00,NaN,NaN,NaN,Scripps Research,La Jolla CA,USA
986,1022,Douglas,Diamond,male,25/10/1953,USA,Chicago IL,US,0000-00-00,NaN,NaN,NaN,University of Chicago,Chicago IL,USA
987,1015,Carolyn,Bertozzi,female,10/10/1966,USA,Boston MA,US,0000-00-00,NaN,NaN,NaN,Stanford University,Stanford CA,USA
988,1023,Philip,Dybvig,male,22/05/1955,USA,Gainesville FL,US,0000-00-00,NaN,NaN,NaN,Washington University,St. Louis MO,USA

In [119]:
premios = pd.read_csv("https://raw.githubusercontent.com/anaepm/rep/refs/heads/main/nobel_data.csv")
premios

,Year,Laureate_Id,Firstname,Lastname,Category,Prize_Share,Motivation
0,1901,1,Wilhelm Conrad,Röntgen,physics,1,"""in recognition of the extraordinary services ..."
1,1901,293,Emil,von Behring,medicine,1,"""for his work on serum therapy especially its ..."
2,1901,462,Henry,Dunant,peace,2,"""for his humanitarian efforts to help wounded ..."
3,1901,463,Frédéric,Passy,peace,2,"""for his lifelong work for international peace..."
4,1901,569,Sully,Prudhomme,literature,1,"""in special recognition of his poetic composit..."
...,...,...,...,...,...,...,...
984,2022,1011,Svante,Pääbo,medicine,1,"""for his discoveries concerning the genomes of..."
985,2022,743,Barry,Sharpless,chemistry,3,"""for the development of click chemistry and bi..."
986,2022,1022,Douglas,Diamond,economics,3,"""for research on banks and financial crises"""
987,2022,1015,Carolyn,Bertozzi,chemistry,3,"""for the development of click chemistry and bi..."
988,2022,1023,Philip,Dybvig,economics,3,"""for research on banks and financial crises"""

## Datos nulos

In [120]:
print(personal.isna().sum())

Laureate_Id               0
Firstname                 0
Lastname                 32
Gender                    0
Birth_Date                0
Birth_Country            31
Birth_City               33
Birth_Country_Code       31
Death_Date                0
Death_Country           343
Death_City              349
Death_Country_Code      343
Organization_Name       262
Organization_City       267
Organization_Country    265
dtype: int64

In [121]:
print(premios.isna().sum())

Year            0
Laureate_Id     0
Firstname       0
Lastname       32
Category        0
Prize_Share     0
Motivation      0
dtype: int64

## Datos duplicados

In [122]:
print(premios.duplicated().sum())

0

In [123]:
print(personal.duplicated().sum())

5

In [124]:
personal["Laureate_Id"].duplicated().sum()

np.int64(8)

In [125]:
premios["Laureate_Id"].duplicated().sum()

np.int64(8)

## Limpieza

In [126]:
# Apellido vacío se le agrega "unknown" para no perder información
personal["Lastname"] = personal["Lastname"].fillna("unknown")
premios["Lastname"] = premios["Lastname"].fillna("unknown")

# Quitar espacios
personal["Firstname"] = personal["Firstname"].str.strip()
personal["Lastname"] = personal["Lastname"].str.strip()
premios["Firstname"] = premios["Firstname"].str.strip()
premios["Lastname"] = premios["Lastname"].str.strip()

In [127]:
# Elimnar duplicados en el id principal de personal
personal = personal.drop_duplicates(subset="Laureate_Id")
personal.shape

(981, 15)

In [ ]:
# Elimine la columna con Laureate_Id de la tabla persona por que cuando
# la uni entra en conflicto con la misma columna de la tabla premio

personal = personal.drop(columns="Laureate_Id")

In [ ]:
# Las fechas estan en diferentes formatos, se arreglaran para cuando se usen en PowerBI.
personal["Birth_Year"] = personal["Birth_Date"].str.extract(r"(\d{4})").astype(float)
personal["Death_Year"] = personal["Death_Date"].str.extract(r"(\d{4})").astype(float)

# Algunos valores de año de nacimiento y muerte son 0, le asigne None
personal.loc[personal["Birth_Year"] == 0, "Birth_Year"] = None
personal.loc[personal["Death_Year"] == 0, "Death_Year"] = None

## Realizar el Join

In [ ]:
nobel = premios.merge(personal, on=["Firstname", "Lastname"], how="left")
nobel.head()

,Year,Laureate_Id,Firstname,Lastname,Category,Prize_Share,Motivation,Gender,Birth_Date,Birth_Country,...,Birth_Country_Code,Death_Date,Death_Country,Death_City,Death_Country_Code,Organization_Name,Organization_City,Organization_Country,Birth_Year,Death_Year
0,1901,1,Wilhelm Conrad,Röntgen,physics,1,"""in recognition of the extraordinary services ...",male,1845-03-27,Prussia (now Germany),...,DE,10/02/1923,Germany,Munich,DE,Munich University,Munich,Germany,1845.0,1923.0
1,1901,293,Emil,von Behring,medicine,1,"""for his work on serum therapy especially its ...",male,1854-03-15,Prussia (now Poland),...,PL,31/03/1917,Germany,Marburg,DE,Marburg University,Marburg,Germany,1854.0,1917.0
2,1901,462,Henry,Dunant,peace,2,"""for his humanitarian efforts to help wounded ...",male,1828-05-08,Switzerland,...,CH,30/10/1910,Switzerland,Heiden,CH,NaN,NaN,NaN,1828.0,1910.0
3,1901,463,Frédéric,Passy,peace,2,"""for his lifelong work for international peace...",male,1822-05-20,France,...,FR,12/06/1912,France,Paris,FR,NaN,NaN,NaN,1822.0,1912.0
4,1901,569,Sully,Prudhomme,literature,1,"""in special recognition of his poetic composit...",male,1839-03-16,France,...,FR,07/09/1907,France,Châtenay,FR,NaN,NaN,NaN,1839.0,1907.0

In [ ]:
nobel.to_csv("nobel_scm.csv", index=False)

In [ ]:
# Enlace de GitHub: